application:
  subdomain: moodist
  upstreams:
    - location: /
      backend: http://moodist:8080/
services:
  moodist:
    # upstream: ghcr.io/remvze/moodist:v3.1.1
    image: ghcr.1ms.run/remvze/moodist:v3.1.1
